// Code generated by protoc-gen-go. DO NOT EDIT.
// source: gaffer/kernel.proto

package gaffer

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	duration "github.com/golang/protobuf/ptypes/duration"
	empty "github.com/golang/protobuf/ptypes/empty"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type KernelProcess_Status int32

const (
	KernelProcess_NONE     KernelProcess_Status = 0
	KernelProcess_STARTING KernelProcess_Status = 1
	KernelProcess_RUNNING  KernelProcess_Status = 2
	KernelProcess_STOPPING KernelProcess_Status = 3
	KernelProcess_STOPPED  KernelProcess_Status = 4
	KernelProcess_ZOMBIE   KernelProcess_Status = 5
)

var KernelProcess_Status_name = map[int32]string{
	0: "NONE",
	1: "STARTING",
	2: "RUNNING",
	3: "STOPPING",
	4: "STOPPED",
	5: "ZOMBIE",
}

var KernelProcess_Status_value = map[string]int32{
	"NONE":     0,
	"STARTING": 1,
	"RUNNING":  2,
	"STOPPING": 3,
	"STOPPED":  4,
	"ZOMBIE":   5,
}

func (x KernelProcess_Status) String() string {
	return proto.EnumName(KernelProcess_Status_name, int32(x))
}

func (KernelProcess_Status) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_b7683b100b2849c5, []int{3, 0}
}

// A service defintion is used to start a process
type KernelService struct {
	Path                 string             `protobuf:"bytes,1,opt,name=path,proto3" json:"path,omitempty"`
	Wd                   string             `protobuf:"bytes,2,opt,name=wd,proto3" json:"wd,omitempty"`
	User                 string             `protobuf:"bytes,4,opt,name=user,proto3" json:"user,omitempty"`
	Group                string             `protobuf:"bytes,5,opt,name=group,proto3" json:"group,omitempty"`
	Args                 []string           `protobuf:"bytes,6,rep,name=args,proto3" json:"args,omitempty"`
	Timeout              *duration.Duration `protobuf:"bytes,7,opt,name=timeout,proto3" json:"timeout,omitempty"`
	Sid                  uint32             `protobuf:"varint,8,opt,name=sid,proto3" json:"sid,omitempty"`
	XXX_NoUnkeyedLiteral struct{}           `json:"-"`
	XXX_unrecognized     []byte             `json:"-"`
	XXX_sizecache        int32              `json:"-"`
}

func (m *KernelService) Reset()         { *m = KernelService{} }
func (m *KernelService) String() string { return proto.CompactTextString(m) }
func (*KernelService) ProtoMessage()    {}
func (*KernelService) Descriptor() ([]byte, []int) {
	return fileDescriptor_b7683b100b2849c5, []int{0}
}

func (m *KernelService) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_KernelService.Unmarshal(m, b)
}
func (m *KernelService) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_KernelService.Marshal(b, m, deterministic)
}
func (m *KernelService) XXX_Merge(src proto.Message) {
	xxx_messageInfo_KernelService.Merge(m, src)
}
func (m *KernelService) XXX_Size() int {
	return xxx_messageInfo_KernelService.Size(m)
}
func (m *KernelService) XXX_DiscardUnknown() {
	xxx_messageInfo_KernelService.DiscardUnknown(m)
}

var xxx_messageInfo_KernelService proto.InternalMessageInfo

func (m *KernelService) GetPath() string {
	if m != nil {
		return m.Path
	}
	return ""
}

func (m *KernelService) GetWd() string {
	if m != nil {
		return m.Wd
	}
	return ""
}

func (m *KernelService) GetUser() string {
	if m != nil {
		return m.User
	}
	return ""
}

func (m *KernelService) GetGroup() string {
	if m != nil {
		return m.Group
	}
	return ""
}

func (m *KernelService) GetArgs() []string {
	if m != nil {
		return m.Args
	}
	return nil
}

func (m *KernelService) GetTimeout() *duration.Duration {
	if m != nil {
		return m.Timeout
	}
	return nil
}

func (m *KernelService) GetSid() uint32 {
	if m != nil {
		return m.Sid
	}
	return 0
}

// A returned process identifier
type KernelProcessId struct {
	Id                   uint32   `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Sid                  uint32   `protobuf:"varint,2,opt,name=sid,proto3" json:"sid,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *KernelProcessId) Reset()         { *m = KernelProcessId{} }
func (m *KernelProcessId) String() string { return proto.CompactTextString(m) }
func (*KernelProcessId) ProtoMessage()    {}
func (*KernelProcessId) Descriptor() ([]byte, []int) {
	return fileDescriptor_b7683b100b2849c5, []int{1}
}

func (m *KernelProcessId) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_KernelProcessId.Unmarshal(m, b)
}
func (m *KernelProcessId) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_KernelProcessId.Marshal(b, m, deterministic)
}
func (m *KernelProcessId) XXX_Merge(src proto.Message) {
	xxx_messageInfo_KernelProcessId.Merge(m, src)
}
func (m *KernelProcessId) XXX_Size() int {
	return xxx_messageInfo_KernelProcessId.Size(m)
}
func (m *KernelProcessId) XXX_DiscardUnknown() {
	xxx_messageInfo_KernelProcessId.DiscardUnknown(m)
}

var xxx_messageInfo_KernelProcessId proto.InternalMessageInfo

func (m *KernelProcessId) GetId() uint32 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *KernelProcessId) GetSid() uint32 {
	if m != nil {
		return m.Sid
	}
	return 0
}

// Return a list of processes
type KernelProcessList struct {
	Process              []*KernelProcess `protobuf:"bytes,1,rep,name=process,proto3" json:"process,omitempty"`
	XXX_NoUnkeyedLiteral struct{}         `json:"-"`
	XXX_unrecognized     []byte           `json:"-"`
	XXX_sizecache        int32            `json:"-"`
}

func (m *KernelProcessList) Reset()         { *m = KernelProcessList{} }
func (m *KernelProcessList) String() string { return proto.CompactTextString(m) }
func (*KernelProcessList) ProtoMessage()    {}
func (*KernelProcessList) Descriptor() ([]byte, []int) {
	return fileDescriptor_b7683b100b2849c5, []int{2}
}

func (m *KernelProcessList) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_KernelProcessList.Unmarshal(m, b)
}
func (m *KernelProcessList) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_KernelProcessList.Marshal(b, m, deterministic)
}
func (m *KernelProcessList) XXX_Merge(src proto.Message) {
	xxx_messageInfo_KernelProcessList.Merge(m, src)
}
func (m *KernelProcessList) XXX_Size() int {
	return xxx_messageInfo_KernelProcessList.Size(m)
}
func (m *KernelProcessList) XXX_DiscardUnknown() {
	xxx_messageInfo_KernelProcessList.DiscardUnknown(m)
}

var xxx_messageInfo_KernelProcessList proto.InternalMessageInfo

func (m *KernelProcessList) GetProcess() []*KernelProcess {
	if m != nil {
		return m.Process
	}
	return nil
}

// Return information about a process
type KernelProcess struct {
	Id                   *KernelProcessId     `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Status               KernelProcess_Status `protobuf:"varint,2,opt,name=status,proto3,enum=gaffer.KernelProcess_Status" json:"status,omitempty"`
	Service              *KernelService       `protobuf:"bytes,3,opt,name=service,proto3" json:"service,omitempty"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-"`
	XXX_unrecognized     []byte               `json:"-"`
	XXX_sizecache        int32                `json:"-"`
}

func (m *KernelProcess) Reset()         { *m = KernelProcess{} }
func (m *KernelProcess) String() string { return proto.CompactTextString(m) }
func (*KernelProcess) ProtoMessage()    {}
func (*KernelProcess) Descriptor() ([]byte, []int) {
	return fileDescriptor_b7683b100b2849c5, []int{3}
}

func (m *KernelProcess) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_KernelProcess.Unmarshal(m, b)
}
func (m *KernelProcess) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_KernelProcess.Marshal(b, m, deterministic)
}
func (m *KernelProcess) XXX_Merge(src proto.Message) {
	xxx_messageInfo_KernelProcess.Merge(m, src)
}
func (m *KernelProcess) XXX_Size() int {
	return xxx_messageInfo_KernelProcess.Size(m)
}
func (m *KernelProcess) XXX_DiscardUnknown() {
	xxx_messageInfo_KernelProcess.DiscardUnknown(m)
}

var xxx_messageInfo_KernelProcess proto.InternalMessageInfo

func (m *KernelProcess) GetId() *KernelProcessId {
	if m != nil {
		return m.Id
	}
	return nil
}

func (m *KernelProcess) GetStatus() KernelProcess_Status {
	if m != nil {
		return m.Status
	}
	return KernelProcess_NONE
}

func (m *KernelProcess) GetService() *KernelService {
	if m != nil {
		return m.Service
	}
	return nil
}

func init() {
	proto.RegisterEnum("gaffer.KernelProcess_Status", KernelProcess_Status_name, KernelProcess_Status_value)
	proto.RegisterType((*KernelService)(nil), "gaffer.KernelService")
	proto.RegisterType((*KernelProcessId)(nil), "gaffer.KernelProcessId")
	proto.RegisterType((*KernelProcessList)(nil), "gaffer.KernelProcessList")
	proto.RegisterType((*KernelProcess)(nil), "gaffer.KernelProcess")
}

func init() {
	proto.RegisterFile("gaffer/kernel.proto", fileDescriptor_b7683b100b2849c5)
}

var fileDescriptor_b7683b100b2849c5 = []byte{
	// 447 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x74, 0x92, 0x4d, 0x6f, 0xd3, 0x40,
	0x10, 0x86, 0xf1, 0x47, 0x9c, 0x74, 0x42, 0x8a, 0x19, 0xbe, 0xb6, 0x06, 0x21, 0x2b, 0x17, 0x72,
	0x72, 0x24, 0x07, 0x71, 0xad, 0x80, 0x44, 0x28, 0x02, 0x9c, 0x68, 0x13, 0x2e, 0xdc, 0xdc, 0x7a,
	0x63, 0x2c, 0xda, 0xd8, 0xda, 0x5d, 0x53, 0xf1, 0xcf, 0x38, 0xf3, 0x9f, 0xb8, 0xa3, 0xdd, 0xb5,
	0x8b, 0x1a, 0x9c, 0xdb, 0xcc, 0xbc, 0xcf, 0xec, 0xbc, 0x9e, 0x31, 0x3c, 0xca, 0xd3, 0xdd, 0x8e,
	0xf1, 0xe9, 0x77, 0xc6, 0xf7, 0xec, 0x2a, 0xaa, 0x78, 0x29, 0x4b, 0xf4, 0x4c, 0x31, 0x78, 0x9e,
	0x97, 0x65, 0x7e, 0xc5, 0xa6, 0xba, 0x7a, 0x51, 0xef, 0xa6, 0xec, 0xba, 0x92, 0x3f, 0x0d, 0x14,
	0xbc, 0x3c, 0x14, 0xb3, 0x9a, 0xa7, 0xb2, 0x28, 0xf7, 0x46, 0x1f, 0xff, 0xb2, 0x60, 0xf4, 0x51,
	0xbf, 0xba, 0x61, 0xfc, 0x47, 0x71, 0xc9, 0x10, 0xc1, 0xad, 0x52, 0xf9, 0x8d, 0x58, 0xa1, 0x35,
	0x39, 0xa1, 0x3a, 0xc6, 0x53, 0xb0, 0x6f, 0x32, 0x62, 0xeb, 0x8a, 0x7d, 0x93, 0x29, 0xa6, 0x16,
	0x8c, 0x13, 0xd7, 0x30, 0x2a, 0xc6, 0xc7, 0xd0, 0xcb, 0x79, 0x59, 0x57, 0xa4, 0xa7, 0x8b, 0x26,
	0x51, 0x64, 0xca, 0x73, 0x41, 0xbc, 0xd0, 0x51, 0xa4, 0x8a, 0x71, 0x06, 0x7d, 0x59, 0x5c, 0xb3,
	0xb2, 0x96, 0xa4, 0x1f, 0x5a, 0x93, 0x61, 0x7c, 0x16, 0x19, 0x97, 0x51, 0xeb, 0x32, 0x9a, 0x37,
	0x2e, 0x69, 0x4b, 0xa2, 0x0f, 0x8e, 0x28, 0x32, 0x32, 0x08, 0xad, 0xc9, 0x88, 0xaa, 0x70, 0x3c,
	0x83, 0x07, 0xc6, 0xf9, 0x9a, 0x97, 0x97, 0x4c, 0x88, 0x65, 0xa6, 0x7c, 0x16, 0x99, 0x76, 0x3e,
	0xa2, 0x76, 0x91, 0xb5, 0x4d, 0xf6, 0xbf, 0xa6, 0x39, 0x3c, 0xbc, 0xd3, 0xf4, 0xa9, 0x10, 0x12,
	0xa7, 0xd0, 0xaf, 0x4c, 0x4a, 0xac, 0xd0, 0x99, 0x0c, 0xe3, 0x27, 0x91, 0xd9, 0x6d, 0x74, 0x87,
	0xa5, 0x2d, 0x35, 0xfe, 0x73, 0xbb, 0xb5, 0x46, 0xc2, 0x57, 0xb7, 0x93, 0x87, 0xf1, 0xb3, 0xce,
	0xee, 0x65, 0xa6, 0x2d, 0xbd, 0x06, 0x4f, 0xc8, 0x54, 0xd6, 0x42, 0xbb, 0x3a, 0x8d, 0x5f, 0x74,
	0xc2, 0xd1, 0x46, 0x33, 0xb4, 0x61, 0x95, 0x43, 0x61, 0xee, 0x43, 0x1c, 0x3d, 0xe3, 0xc0, 0x61,
	0x73, 0x3c, 0xda, 0x52, 0xe3, 0x2d, 0x78, 0xe6, 0x09, 0x1c, 0x80, 0x9b, 0xac, 0x92, 0x85, 0x7f,
	0x0f, 0xef, 0xc3, 0x60, 0xb3, 0x7d, 0x4b, 0xb7, 0xcb, 0xe4, 0x83, 0x6f, 0xe1, 0x10, 0xfa, 0xf4,
	0x4b, 0x92, 0xa8, 0xc4, 0x36, 0xd2, 0x6a, 0xbd, 0x56, 0x99, 0xa3, 0x24, 0x9d, 0x2d, 0xe6, 0xbe,
	0x8b, 0x00, 0xde, 0xd7, 0xd5, 0xe7, 0x77, 0xcb, 0x85, 0xdf, 0x8b, 0x7f, 0x5b, 0xe0, 0x99, 0x81,
	0xf8, 0x06, 0xdc, 0x75, 0xb1, 0xcf, 0xf1, 0xe9, 0x7f, 0xb7, 0x5b, 0xa8, 0xdf, 0x2f, 0x38, 0x52,
	0xc7, 0x73, 0x18, 0xbd, 0xe7, 0x2c, 0x95, 0xac, 0xdd, 0x5c, 0xf7, 0x97, 0x04, 0xc7, 0x96, 0x88,
	0xe7, 0x70, 0xd2, 0x24, 0x4c, 0xe0, 0x31, 0x2a, 0x38, 0xeb, 0x14, 0xd4, 0xb5, 0x2f, 0x3c, 0xed,
	0x68, 0xf6, 0x37, 0x00, 0x00, 0xff, 0xff, 0x9f, 0xa7, 0x79, 0x70, 0x55, 0x03, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConnInterface

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion6

// KernelClient is the client API for Kernel service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type KernelClient interface {
	// Simple ping method to show server is "up"
	Ping(ctx context.Context, in *empty.Empty, opts ...grpc.CallOption) (*empty.Empty, error)
	// Create a new process
	CreateProcess(ctx context.Context, in *KernelService, opts ...grpc.CallOption) (*KernelProcessId, error)
	// Return filtered list of processes
	Processes(ctx context.Context, in *KernelProcessId, opts ...grpc.CallOption) (*KernelProcessList, error)
}

type kernelClient struct {
	cc grpc.ClientConnInterface
}

func NewKernelClient(cc grpc.ClientConnInterface) KernelClient {
	return &kernelClient{cc}
}

func (c *kernelClient) Ping(ctx context.Context, in *empty.Empty, opts ...grpc.CallOption) (*empty.Empty, error) {
	out := new(empty.Empty)
	err := c.cc.Invoke(ctx, "/gaffer.Kernel/Ping", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *kernelClient) CreateProcess(ctx context.Context, in *KernelService, opts ...grpc.CallOption) (*KernelProcessId, error) {
	out := new(KernelProcessId)
	err := c.cc.Invoke(ctx, "/gaffer.Kernel/CreateProcess", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *kernelClient) Processes(ctx context.Context, in *KernelProcessId, opts ...grpc.CallOption) (*KernelProcessList, error) {
	out := new(KernelProcessList)
	err := c.cc.Invoke(ctx, "/gaffer.Kernel/Processes", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// KernelServer is the server API for Kernel service.
type KernelServer interface {
	// Simple ping method to show server is "up"
	Ping(context.Context, *empty.Empty) (*empty.Empty, error)
	// Create a new process
	CreateProcess(context.Context, *KernelService) (*KernelProcessId, error)
	// Return filtered list of processes
	Processes(context.Context, *KernelProcessId) (*KernelProcessList, error)
}

// UnimplementedKernelServer can be embedded to have forward compatible implementations.
type UnimplementedKernelServer struct {
}

func (*UnimplementedKernelServer) Ping(ctx context.Context, req *empty.Empty) (*empty.Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Ping not implemented")
}
func (*UnimplementedKernelServer) CreateProcess(ctx context.Context, req *KernelService) (*KernelProcessId, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateProcess not implemented")
}
func (*UnimplementedKernelServer) Processes(ctx context.Context, req *KernelProcessId) (*KernelProcessList, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Processes not implemented")
}

func RegisterKernelServer(s *grpc.Server, srv KernelServer) {
	s.RegisterService(&_Kernel_serviceDesc, srv)
}

func _Kernel_Ping_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(empty.Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(KernelServer).Ping(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/gaffer.Kernel/Ping",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(KernelServer).Ping(ctx, req.(*empty.Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _Kernel_CreateProcess_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(KernelService)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(KernelServer).CreateProcess(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/gaffer.Kernel/CreateProcess",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(KernelServer).CreateProcess(ctx, req.(*KernelService))
	}
	return interceptor(ctx, in, info, handler)
}

func _Kernel_Processes_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(KernelProcessId)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(KernelServer).Processes(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/gaffer.Kernel/Processes",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(KernelServer).Processes(ctx, req.(*KernelProcessId))
	}
	return interceptor(ctx, in, info, handler)
}

var _Kernel_serviceDesc = grpc.ServiceDesc{
	ServiceName: "gaffer.Kernel",
	HandlerType: (*KernelServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Ping",
			Handler:    _Kernel_Ping_Handler,
		},
		{
			MethodName: "CreateProcess",
			Handler:    _Kernel_CreateProcess_Handler,
		},
		{
			MethodName: "Processes",
			Handler:    _Kernel_Processes_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "gaffer/kernel.proto",
}
