// Code generated by protoc-gen-go. DO NOT EDIT.
// source: gaffer/service.proto

package gaffer

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

// A service definition is used to start one or more processes
type Service struct {
	Sid                  uint32   `protobuf:"varint,1,opt,name=sid,proto3" json:"sid,omitempty"`
	Name                 string   `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Path                 string   `protobuf:"bytes,3,opt,name=path,proto3" json:"path,omitempty"`
	Cwd                  string   `protobuf:"bytes,4,opt,name=cwd,proto3" json:"cwd,omitempty"`
	Args                 []string `protobuf:"bytes,5,rep,name=args,proto3" json:"args,omitempty"`
	User                 string   `protobuf:"bytes,6,opt,name=user,proto3" json:"user,omitempty"`
	Group                string   `protobuf:"bytes,7,opt,name=group,proto3" json:"group,omitempty"`
	Enabled              bool     `protobuf:"varint,8,opt,name=enabled,proto3" json:"enabled,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Service) Reset()         { *m = Service{} }
func (m *Service) String() string { return proto.CompactTextString(m) }
func (*Service) ProtoMessage()    {}
func (*Service) Descriptor() ([]byte, []int) {
	return fileDescriptor_d89f813df1b8899b, []int{0}
}

func (m *Service) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Service.Unmarshal(m, b)
}
func (m *Service) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Service.Marshal(b, m, deterministic)
}
func (m *Service) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Service.Merge(m, src)
}
func (m *Service) XXX_Size() int {
	return xxx_messageInfo_Service.Size(m)
}
func (m *Service) XXX_DiscardUnknown() {
	xxx_messageInfo_Service.DiscardUnknown(m)
}

var xxx_messageInfo_Service proto.InternalMessageInfo

func (m *Service) GetSid() uint32 {
	if m != nil {
		return m.Sid
	}
	return 0
}

func (m *Service) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Service) GetPath() string {
	if m != nil {
		return m.Path
	}
	return ""
}

func (m *Service) GetCwd() string {
	if m != nil {
		return m.Cwd
	}
	return ""
}

func (m *Service) GetArgs() []string {
	if m != nil {
		return m.Args
	}
	return nil
}

func (m *Service) GetUser() string {
	if m != nil {
		return m.User
	}
	return ""
}

func (m *Service) GetGroup() string {
	if m != nil {
		return m.Group
	}
	return ""
}

func (m *Service) GetEnabled() bool {
	if m != nil {
		return m.Enabled
	}
	return false
}

// Return a list of services
type ServiceList struct {
	Service              []*Service `protobuf:"bytes,1,rep,name=service,proto3" json:"service,omitempty"`
	XXX_NoUnkeyedLiteral struct{}   `json:"-"`
	XXX_unrecognized     []byte     `json:"-"`
	XXX_sizecache        int32      `json:"-"`
}

func (m *ServiceList) Reset()         { *m = ServiceList{} }
func (m *ServiceList) String() string { return proto.CompactTextString(m) }
func (*ServiceList) ProtoMessage()    {}
func (*ServiceList) Descriptor() ([]byte, []int) {
	return fileDescriptor_d89f813df1b8899b, []int{1}
}

func (m *ServiceList) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ServiceList.Unmarshal(m, b)
}
func (m *ServiceList) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ServiceList.Marshal(b, m, deterministic)
}
func (m *ServiceList) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ServiceList.Merge(m, src)
}
func (m *ServiceList) XXX_Size() int {
	return xxx_messageInfo_ServiceList.Size(m)
}
func (m *ServiceList) XXX_DiscardUnknown() {
	xxx_messageInfo_ServiceList.DiscardUnknown(m)
}

var xxx_messageInfo_ServiceList proto.InternalMessageInfo

func (m *ServiceList) GetService() []*Service {
	if m != nil {
		return m.Service
	}
	return nil
}

// A service identifier
type ServiceId struct {
	Sid                  uint32   `protobuf:"varint,1,opt,name=sid,proto3" json:"sid,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ServiceId) Reset()         { *m = ServiceId{} }
func (m *ServiceId) String() string { return proto.CompactTextString(m) }
func (*ServiceId) ProtoMessage()    {}
func (*ServiceId) Descriptor() ([]byte, []int) {
	return fileDescriptor_d89f813df1b8899b, []int{2}
}

func (m *ServiceId) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ServiceId.Unmarshal(m, b)
}
func (m *ServiceId) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ServiceId.Marshal(b, m, deterministic)
}
func (m *ServiceId) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ServiceId.Merge(m, src)
}
func (m *ServiceId) XXX_Size() int {
	return xxx_messageInfo_ServiceId.Size(m)
}
func (m *ServiceId) XXX_DiscardUnknown() {
	xxx_messageInfo_ServiceId.DiscardUnknown(m)
}

var xxx_messageInfo_ServiceId proto.InternalMessageInfo

func (m *ServiceId) GetSid() uint32 {
	if m != nil {
		return m.Sid
	}
	return 0
}

func init() {
	proto.RegisterType((*Service)(nil), "gaffer.Service")
	proto.RegisterType((*ServiceList)(nil), "gaffer.ServiceList")
	proto.RegisterType((*ServiceId)(nil), "gaffer.ServiceId")
}

func init() {
	proto.RegisterFile("gaffer/service.proto", fileDescriptor_d89f813df1b8899b)
}

var fileDescriptor_d89f813df1b8899b = []byte{
	// 216 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x64, 0x90, 0xc1, 0x4a, 0xc4, 0x30,
	0x10, 0x86, 0x89, 0xd9, 0x6d, 0x76, 0x67, 0x11, 0x25, 0xec, 0x61, 0x2e, 0x42, 0xe8, 0x29, 0x5e,
	0x2a, 0xe8, 0xc5, 0x57, 0x10, 0x3c, 0xc5, 0x27, 0xc8, 0x36, 0x69, 0x2d, 0x68, 0x5b, 0x92, 0x56,
	0x9f, 0xca, 0x77, 0x94, 0x49, 0xd2, 0xd3, 0xde, 0xbe, 0xf9, 0xe6, 0x1f, 0xc8, 0x1f, 0x38, 0xf7,
	0xb6, 0xeb, 0x7c, 0x78, 0x8a, 0x3e, 0xfc, 0x0c, 0xad, 0x6f, 0xe6, 0x30, 0x2d, 0x93, 0xac, 0xb2,
	0xad, 0xff, 0x18, 0x88, 0x8f, 0xbc, 0x91, 0xf7, 0xc0, 0xe3, 0xe0, 0x90, 0x29, 0xa6, 0x6f, 0x0d,
	0xa1, 0x94, 0xb0, 0x1b, 0xed, 0xb7, 0xc7, 0x1b, 0xc5, 0xf4, 0xd1, 0x24, 0x26, 0x37, 0xdb, 0xe5,
	0x13, 0x79, 0x76, 0xc4, 0x74, 0xd9, 0xfe, 0x3a, 0xdc, 0x25, 0x45, 0x48, 0x29, 0x1b, 0xfa, 0x88,
	0x7b, 0xc5, 0x29, 0x45, 0x4c, 0x6e, 0x8d, 0x3e, 0x60, 0x95, 0x2f, 0x89, 0xe5, 0x19, 0xf6, 0x7d,
	0x98, 0xd6, 0x19, 0x45, 0x92, 0x79, 0x90, 0x08, 0xc2, 0x8f, 0xf6, 0xf2, 0xe5, 0x1d, 0x1e, 0x14,
	0xd3, 0x07, 0xb3, 0x8d, 0xf5, 0x2b, 0x9c, 0xca, 0x73, 0xdf, 0x87, 0xb8, 0xc8, 0x47, 0x10, 0xa5,
	0x17, 0x32, 0xc5, 0xf5, 0xe9, 0xf9, 0xae, 0xc9, 0xc5, 0x9a, 0x92, 0x32, 0xdb, 0xbe, 0x7e, 0x80,
	0x63, 0x71, 0x6f, 0xee, 0xba, 0xea, 0xa5, 0x4a, 0xff, 0xf2, 0xf2, 0x1f, 0x00, 0x00, 0xff, 0xff,
	0x3a, 0x55, 0x5a, 0xac, 0x2f, 0x01, 0x00, 0x00,
}
